# client/dockerfile

# Node.js 기반 React 클라이언트 빌드
FROM node:20-alpine AS build

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 서버 코드 복사
COPY . ./
RUN npm run build

# Nginx를 사용해 정적 파일 서빙
FROM nginx:alpine

# 빌드 결과물을 Nginx의 html 디렉토리로 복사
COPY --from=build /app/build /usr/share/nginx/html

# 포트 80 노출 (외부에 직접 노출하지 않음)
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
